#############################################################################
# Makefile for building: SerialPlot.app/Contents/MacOS/SerialPlot
# Generated by qmake (2.01a) (Qt 4.7.3) on: Sat Nov 12 11:06:01 2011
# Project:  SerialPlot.pro
# Template: app
# Command: /Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/qmake -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile SerialPlot.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -I. -I../../../QtSDK/Desktop/Qt/473/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/473/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../../QtSDK/Desktop/Qt/473/gcc/include -I../qwt-6.0.1/src -I../qextserialport/src -I. -I. -F/Users/peter/QtSDK/Desktop/Qt/473/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/peter/QtSDK/Desktop/Qt/473/gcc/lib -L/Users/peter/QtSDK/Desktop/Qt/473/gcc/lib -F/Users/peter/Documents/Qt/SerialPlot/../qwt-6.0.1/lib/ -framework qwt -L/Users/peter/Documents/Qt/SerialPlot/../qextserialport/src/build/ -lqextserialport -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		SensorCurve.cpp \
		SensorData.cpp \
		DynamicParam.cpp \
		serialSelectDialog.cpp \
		PlotWindow.cpp \
		ParamWindow.cpp moc_mainwindow.cpp \
		moc_DynamicParam.cpp \
		moc_serialSelectDialog.cpp \
		moc_PlotWindow.cpp \
		moc_ParamWindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		SensorCurve.o \
		SensorData.o \
		DynamicParam.o \
		serialSelectDialog.o \
		PlotWindow.o \
		ParamWindow.o \
		moc_mainwindow.o \
		moc_DynamicParam.o \
		moc_serialSelectDialog.o \
		moc_PlotWindow.o \
		moc_ParamWindow.o
DIST          = ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		SerialPlot.pro
QMAKE_TARGET  = SerialPlot
DESTDIR       = 
TARGET        = SerialPlot.app/Contents/MacOS/SerialPlot

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile SerialPlot.app/Contents/PkgInfo SerialPlot.app/Contents/Resources/empty.lproj SerialPlot.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_serialSelectDialog.h ui_PlotWindow.h ui_ParamWindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) SerialPlot.app/Contents/MacOS/ || $(MKDIR) SerialPlot.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SerialPlot.pro  ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++/qmake.conf ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile SerialPlot.pro
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile SerialPlot.pro

SerialPlot.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) SerialPlot.app/Contents || $(MKDIR) SerialPlot.app/Contents 
	@$(DEL_FILE) SerialPlot.app/Contents/PkgInfo
	@echo "APPL????" >SerialPlot.app/Contents/PkgInfo
SerialPlot.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) SerialPlot.app/Contents/Resources || $(MKDIR) SerialPlot.app/Contents/Resources 
	@touch SerialPlot.app/Contents/Resources/empty.lproj
	
SerialPlot.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) SerialPlot.app/Contents || $(MKDIR) SerialPlot.app/Contents 
	@$(DEL_FILE) SerialPlot.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,SerialPlot,g" -e "s,@TYPEINFO@,????,g" ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/macx-g++/Info.plist.app >SerialPlot.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/SerialPlot1.0.0 || $(MKDIR) .tmp/SerialPlot1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SerialPlot1.0.0/ && $(COPY_FILE) --parents mainwindow.h SensorCurve.h SensorData.h DynamicParam.h serialSelectDialog.h PlotWindow.h ParamWindow.h .tmp/SerialPlot1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp SensorCurve.cpp SensorData.cpp DynamicParam.cpp serialSelectDialog.cpp PlotWindow.cpp ParamWindow.cpp .tmp/SerialPlot1.0.0/ && $(COPY_FILE) --parents mainwindow.ui serialSelectDialog.ui PlotWindow.ui ParamWindow.ui .tmp/SerialPlot1.0.0/ && (cd `dirname .tmp/SerialPlot1.0.0` && $(TAR) SerialPlot1.0.0.tar SerialPlot1.0.0 && $(COMPRESS) SerialPlot1.0.0.tar) && $(MOVE) `dirname .tmp/SerialPlot1.0.0`/SerialPlot1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SerialPlot1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r SerialPlot.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_DynamicParam.cpp moc_serialSelectDialog.cpp moc_PlotWindow.cpp moc_ParamWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_DynamicParam.cpp moc_serialSelectDialog.cpp moc_PlotWindow.cpp moc_ParamWindow.cpp
moc_mainwindow.cpp: ../qextserialport/src/qextserialport.h \
		../qextserialport/src/qextserialport_global.h \
		PlotWindow.h \
		SensorCurve.h \
		../qwt-6.0.1/src/qwt_plot_curve.h \
		../qwt-6.0.1/src/qwt_global.h \
		../qwt-6.0.1/src/qwt_plot_seriesitem.h \
		../qwt-6.0.1/src/qwt_plot_item.h \
		../qwt-6.0.1/src/qwt_legend_itemmanager.h \
		../qwt-6.0.1/src/qwt_text.h \
		../qwt-6.0.1/src/qwt_scale_div.h \
		../qwt-6.0.1/src/qwt_interval.h \
		../qwt-6.0.1/src/qwt_series_data.h \
		../qwt-6.0.1/src/qwt_point_3d.h \
		../qwt-6.0.1/src/qwt_point_polar.h \
		../qwt-6.0.1/src/qwt_math.h \
		SensorData.h \
		DynamicParam.h \
		mainwindow.h
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_DynamicParam.cpp: DynamicParam.h
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ DynamicParam.h -o moc_DynamicParam.cpp

moc_serialSelectDialog.cpp: serialSelectDialog.h
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ serialSelectDialog.h -o moc_serialSelectDialog.cpp

moc_PlotWindow.cpp: SensorCurve.h \
		../qwt-6.0.1/src/qwt_plot_curve.h \
		../qwt-6.0.1/src/qwt_global.h \
		../qwt-6.0.1/src/qwt_plot_seriesitem.h \
		../qwt-6.0.1/src/qwt_plot_item.h \
		../qwt-6.0.1/src/qwt_legend_itemmanager.h \
		../qwt-6.0.1/src/qwt_text.h \
		../qwt-6.0.1/src/qwt_scale_div.h \
		../qwt-6.0.1/src/qwt_interval.h \
		../qwt-6.0.1/src/qwt_series_data.h \
		../qwt-6.0.1/src/qwt_point_3d.h \
		../qwt-6.0.1/src/qwt_point_polar.h \
		../qwt-6.0.1/src/qwt_math.h \
		SensorData.h \
		PlotWindow.h
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ PlotWindow.h -o moc_PlotWindow.cpp

moc_ParamWindow.cpp: ParamWindow.h
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ParamWindow.h -o moc_ParamWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_serialSelectDialog.h ui_PlotWindow.h ui_ParamWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_serialSelectDialog.h ui_PlotWindow.h ui_ParamWindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_serialSelectDialog.h: serialSelectDialog.ui
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/uic serialSelectDialog.ui -o ui_serialSelectDialog.h

ui_PlotWindow.h: PlotWindow.ui
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/uic PlotWindow.ui -o ui_PlotWindow.h

ui_ParamWindow.h: ParamWindow.ui
	/Users/peter/QtSDK/Desktop/Qt/473/gcc/bin/uic ParamWindow.ui -o ui_ParamWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../qextserialport/src/qextserialport.h \
		../qextserialport/src/qextserialport_global.h \
		PlotWindow.h \
		SensorCurve.h \
		../qwt-6.0.1/src/qwt_plot_curve.h \
		../qwt-6.0.1/src/qwt_global.h \
		../qwt-6.0.1/src/qwt_plot_seriesitem.h \
		../qwt-6.0.1/src/qwt_plot_item.h \
		../qwt-6.0.1/src/qwt_legend_itemmanager.h \
		../qwt-6.0.1/src/qwt_text.h \
		../qwt-6.0.1/src/qwt_scale_div.h \
		../qwt-6.0.1/src/qwt_interval.h \
		../qwt-6.0.1/src/qwt_series_data.h \
		../qwt-6.0.1/src/qwt_point_3d.h \
		../qwt-6.0.1/src/qwt_point_polar.h \
		../qwt-6.0.1/src/qwt_math.h \
		SensorData.h \
		DynamicParam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../qextserialport/src/qextserialport.h \
		../qextserialport/src/qextserialport_global.h \
		PlotWindow.h \
		SensorCurve.h \
		../qwt-6.0.1/src/qwt_plot_curve.h \
		../qwt-6.0.1/src/qwt_global.h \
		../qwt-6.0.1/src/qwt_plot_seriesitem.h \
		../qwt-6.0.1/src/qwt_plot_item.h \
		../qwt-6.0.1/src/qwt_legend_itemmanager.h \
		../qwt-6.0.1/src/qwt_text.h \
		../qwt-6.0.1/src/qwt_scale_div.h \
		../qwt-6.0.1/src/qwt_interval.h \
		../qwt-6.0.1/src/qwt_series_data.h \
		../qwt-6.0.1/src/qwt_point_3d.h \
		../qwt-6.0.1/src/qwt_point_polar.h \
		../qwt-6.0.1/src/qwt_math.h \
		SensorData.h \
		DynamicParam.h \
		ui_mainwindow.h \
		../qextserialport/src/qextserialenumerator.h \
		serialSelectDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

SensorCurve.o: SensorCurve.cpp SensorCurve.h \
		../qwt-6.0.1/src/qwt_plot_curve.h \
		../qwt-6.0.1/src/qwt_global.h \
		../qwt-6.0.1/src/qwt_plot_seriesitem.h \
		../qwt-6.0.1/src/qwt_plot_item.h \
		../qwt-6.0.1/src/qwt_legend_itemmanager.h \
		../qwt-6.0.1/src/qwt_text.h \
		../qwt-6.0.1/src/qwt_scale_div.h \
		../qwt-6.0.1/src/qwt_interval.h \
		../qwt-6.0.1/src/qwt_series_data.h \
		../qwt-6.0.1/src/qwt_point_3d.h \
		../qwt-6.0.1/src/qwt_point_polar.h \
		../qwt-6.0.1/src/qwt_math.h \
		SensorData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SensorCurve.o SensorCurve.cpp

SensorData.o: SensorData.cpp SensorData.h \
		../qwt-6.0.1/src/qwt_series_data.h \
		../qwt-6.0.1/src/qwt_global.h \
		../qwt-6.0.1/src/qwt_interval.h \
		../qwt-6.0.1/src/qwt_point_3d.h \
		../qwt-6.0.1/src/qwt_point_polar.h \
		../qwt-6.0.1/src/qwt_math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SensorData.o SensorData.cpp

DynamicParam.o: DynamicParam.cpp DynamicParam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DynamicParam.o DynamicParam.cpp

serialSelectDialog.o: serialSelectDialog.cpp serialSelectDialog.h \
		ui_serialSelectDialog.h \
		../qextserialport/src/qextserialenumerator.h \
		../qextserialport/src/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialSelectDialog.o serialSelectDialog.cpp

PlotWindow.o: PlotWindow.cpp PlotWindow.h \
		SensorCurve.h \
		../qwt-6.0.1/src/qwt_plot_curve.h \
		../qwt-6.0.1/src/qwt_global.h \
		../qwt-6.0.1/src/qwt_plot_seriesitem.h \
		../qwt-6.0.1/src/qwt_plot_item.h \
		../qwt-6.0.1/src/qwt_legend_itemmanager.h \
		../qwt-6.0.1/src/qwt_text.h \
		../qwt-6.0.1/src/qwt_scale_div.h \
		../qwt-6.0.1/src/qwt_interval.h \
		../qwt-6.0.1/src/qwt_series_data.h \
		../qwt-6.0.1/src/qwt_point_3d.h \
		../qwt-6.0.1/src/qwt_point_polar.h \
		../qwt-6.0.1/src/qwt_math.h \
		SensorData.h \
		ui_PlotWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlotWindow.o PlotWindow.cpp

ParamWindow.o: ParamWindow.cpp ParamWindow.h \
		ui_ParamWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParamWindow.o ParamWindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_DynamicParam.o: moc_DynamicParam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DynamicParam.o moc_DynamicParam.cpp

moc_serialSelectDialog.o: moc_serialSelectDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialSelectDialog.o moc_serialSelectDialog.cpp

moc_PlotWindow.o: moc_PlotWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PlotWindow.o moc_PlotWindow.cpp

moc_ParamWindow.o: moc_ParamWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ParamWindow.o moc_ParamWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

